name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.19.x

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo tag_name=${TAG} >> $GITHUB_OUTPUT
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release  --timeout=1h --release-notes=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
