name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.19.x


      - name: Get previous tag
        id: previoustag
        run: |
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

      - name: Display previous tag
        run: |
          echo "Previous tag: ${{ steps.previoustag.outputs.PREVIOUS_TAG }}"

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo tag_name=${TAG} >> $GITHUB_OUTPUT
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release  --timeout=1h --release-notes=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          USERNAME: ${{ github.repository_owner }}
          GORELEASER_PREVIOUS_TAG: ${{ steps.previoustag.outputs.PREVIOUS_TAG }}
